name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  # Memungkinkan workflow dijalankan secara manual dari tab Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.x' # Versi flutter (opsional, disarankan agar stabil)

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        # base-href disesuaikan dengan nama repositori Anda di GitHub.
        # Karena repository Anda adalah "jurnal-harian", maka /jurnal-harian/
        run: flutter build web --release --base-href "/jurnal-harian/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true # Membuat branch gh-pages lebih bersih
